# Cleaning Data And Numerical Analysis

In [1]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [4]:
# we sometimes have incomplete data
d = ['A', 'B', np.nan, 'D']
y = pd.Series(d)
y.isnull() # NaN evaluates to null
y.isna() # we can spot NaN
y.notnull()
y.notna()

0     True
1     True
2    False
3     True
dtype: bool

In [5]:
# there are several strategies to deal with missing data
y.fillna('Q') # does not persist
# careful - we lose the original data structure
y.fillna('Q', inplace=True) # the changes will persist
y

0    A
1    B
2    Q
3    D
dtype: object

In [6]:
# Careful -when we make a copy it is SHALLOW (not a deep copy)
# so if we mutate the original it does NOT mutate the copy
y[2] = np.nan
y.dropna(inplace=True)
y

0    A
1    B
3    D
dtype: object

# Handling Missing Data in a DataFrame

In [7]:
df = pd.DataFrame(np.random.randn(10,3))
df.iloc[0:4,1] = np.nan
df.iloc[1:3,2] = np.nan
# we can fill NaN like this
df.fillna(0) # does not alter the original structure
# axis=1 lets us work across the df
df.fillna(method='ffill', axis=1) # careful - deprecation

C:\Users\eabhahr\AppData\Local\Temp\ipykernel_32988\4015756528.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1) # careful - deprecation

          0         1         2
0 -0.562721 -0.562721 -0.574906
1 -1.046190 -1.046190 -1.046190
2 -0.275367 -0.275367 -0.275367
3  0.616654  0.616654  1.165479
4  1.407512  0.798775  0.276228
5 -1.074104  1.496761 -1.027795
6 -1.040453  0.397211  1.095928
7  0.254119  0.407090 -1.688087
8  0.770760  0.782331 -1.261198
9  0.461968  1.235765 -1.926737

# Statistical Methods

In [8]:
df.describe() # gives useful statistics for the DataFrame
# these ignore NaN

               0         1         2
count  10.000000  6.000000  8.000000
mean   -0.048782  0.852989 -0.492636
std     0.877677  0.441690  1.209110
min    -1.074104  0.397211 -1.926737
25%    -0.921020  0.500900 -1.367920
50%    -0.010624  0.790553 -0.801350
75%     0.577982  1.126517  0.481153
max     1.407512  1.496761  1.165479

In [9]:
df.min()
df.max()
df.count() # they all ignore NaN
df.mean()

0   -0.048782
1    0.852989
2   -0.492636
dtype: float64

In [10]:
# we can use this to fillna
df.fillna( df.mean(), inplace=False) # careful - this will affect other stats

          0         1         2
0 -0.562721  0.852989 -0.574906
1 -1.046190  0.852989 -0.492636
2 -0.275367  0.852989 -0.492636
3  0.616654  0.852989  1.165479
4  1.407512  0.798775  0.276228
5 -1.074104  1.496761 -1.027795
6 -1.040453  0.397211  1.095928
7  0.254119  0.407090 -1.688087
8  0.770760  0.782331 -1.261198
9  0.461968  1.235765 -1.926737

In [11]:
col1_mean = df.iloc[:,1].mean()
col1_mean # the mean value of every significant member of col1
df.fillna(col1_mean) # use any reasonable significant value

          0         1         2
0 -0.562721  0.852989 -0.574906
1 -1.046190  0.852989  0.852989
2 -0.275367  0.852989  0.852989
3  0.616654  0.852989  1.165479
4  1.407512  0.798775  0.276228
5 -1.074104  1.496761 -1.027795
6 -1.040453  0.397211  1.095928
7  0.254119  0.407090 -1.688087
8  0.770760  0.782331 -1.261198
9  0.461968  1.235765 -1.926737