# Introducing Pandas
Pandas is Python And Numerical Data Analysis

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Pandas provides additional data structures
l = [8.0, 7, -5.0, 3, 99]
p = pd.Series(l)
# p = pd.Series(l, index = range(0, 10, 2)) # we may set an index on creation
# a Pandas Series is a mutable collection of the same data type
p.values # the values of a Series are a Numpy array
p.index # a range-like object - there is always an index
ind = ('d', 'b', 'a', 'c', 'd') # a tuple
s = pd.Series(l, index = ind)
s
s.index
s['b':'c'] # normal slicing, but inclusive of start and end value. If index is int, start and element before end.
s['d'] # every match is found - even with repeated index names. index repetition is not recommended.

In [31]:
# building Pandas Series
values = (4,7,-5,3)

ind = {'d', 'b', 'a', 'c'} # set ensures unique numbers
s = pd.Series(values, index=ind)
s
s['b'] # s['b'] doesn't have to be 7. It can be shuffled as the index is a set.

{'a', 'b', 'c', 'd'}

In [32]:
s['d']=99
s.iloc[0] # iloc lets us use the underlying index location
s

d    99
b     7
a    -5
c     3
dtype: int64

In [35]:
# as well as mutating members, we can add members to the Series
s['e'] = -321
# s
s['d':'e':2] # step uses underlying ordinality

d     99
a     -5
e   -321
dtype: int64

In [37]:
# we can use comparative logic to return members
s[s>2] # any comparator is legal here
# we may apply mathematics to all the members
s**0.5  # apply to every member NaN represents 'not a number'

d    9.949874
b    2.645751
a         NaN
c    1.732051
e         NaN
dtype: float64

In [38]:
s.iloc[2] = np.nan
s

d     99.0
b      7.0
a      NaN
c      3.0
e   -321.0
dtype: float64

# Pandas Data Analysis with Data Frames

In [46]:
sdata = {'Cork':35000, 'Dublin':71000, 'Galway':16000, 'Athlone':5000, 'Genoa':500}
idata = {'Cork', 'Dublin', 'Shannon', 'Galway', 'Athlone'} # set, list, tuple all good
p = pd.Series(sdata, index=idata)
p # any missing data members are assigned NaN

Athlone     5000.0
Cork       35000.0
Galway     16000.0
Dublin     71000.0
Shannon        NaN
dtype: float64

In [47]:
p['Cork'] # case-sensitive index
p['Shannon'] = 32345
p

Athlone     5000.0
Cork       35000.0
Galway     16000.0
Dublin     71000.0
Shannon    32345.0
dtype: float64

In [56]:
# Pandas also provides a DataFrame class.
# Each column of a DataFrame is a Series.
# Therefore each column may only contain a single data type.
# The columns of a DataFrame may be of a different data types.
# A DataFrame is somewhat like a spreadsheet.

towns_l = ['Cork', 'Dublin', 'Galway', 'Athlone', 'Shannon', 'Rosscarbery', 'Athenry']
years_l = [2017, 2018, 2019, 2020, 2021, 2022, 2023]
pop_l   = [1.5, 1.7, 3.6, 2.4, 2.9, 3.2, 1.7]

data_d = {'Towns': towns_l, 'Years':years_l, 'Pop':pop_l}
data_d # we have a dictionary

{'Towns': ['Cork',
  'Dublin',
  'Galway',
  'Athlone',
  'Shannon',
  'Rosscarbery',
  'Athenry'],
 'Years': [2017, 2018, 2019, 2020, 2021, 2022, 2023],
 'Pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2, 1.7]}

In [58]:
# we may construct a DataFrame from this dictionary
df = pd.DataFrame(data_d)
# df = pd.DataFrame(data_d, index=towns_l) # index is optional
df # we have a pretty representation of the data

         Towns  Years  Pop
0         Cork   2017  1.5
1       Dublin   2018  1.7
2       Galway   2019  3.6
3      Athlone   2020  2.4
4      Shannon   2021  2.9
5  Rosscarbery   2022  3.2
6      Athenry   2023  1.7

In [61]:
df['Towns'] # we can view single column of a DataFrame
df[['Towns', 'Years']] # A list of columns returns a DataFrame

0           Cork
1         Dublin
2         Galway
3        Athlone
4        Shannon
5    Rosscarbery
6        Athenry
Name: Towns, dtype: object

In [62]:
df.head(3) # first 3 members of DataFrame
df.tail(2) # last 2 members of DataFrame

    Towns  Years  Pop
0    Cork   2017  1.5
1  Dublin   2018  1.7
2  Galway   2019  3.6

In [63]:
# we may re-index at any time
new_ind = ('one', 'two', 'three', 'four', 'five', 'six', 'seven')
df.index = new_ind
df

             Towns  Years  Pop
one           Cork   2017  1.5
two         Dublin   2018  1.7
three       Galway   2019  3.6
four       Athlone   2020  2.4
five       Shannon   2021  2.9
six    Rosscarbery   2022  3.2
seven      Athenry   2023  1.7

In [71]:
# we may use existing data to populate a new DataFrame with specific columns
df2 = pd.DataFrame(data_d, columns=['Pop', 'Years'], index=new_ind)
df2
df3 = df2[['pop']] # we may also make a DataFrame from an existing DataFrame
df3

       Pop  Years
one    1.5   2017
two    1.7   2018
three  3.6   2019
four   2.4   2020
five   2.9   2021
six    3.2   2022
seven  1.7   2023

# Accessing Data within DataFrames

In [81]:
df2.index = towns_l
df2
df2['Pop']
df2.iloc[3] # iloc lets us use the underlying ordinality of the members
df2.loc['Shannon'] # allows us to locate a member from the index - returns the matching row

Pop         2.9
Years    2021.0
Name: Shannon, dtype: float64

In [84]:
# we may use both loc and iloc together

num_l = [4,5,6,3,2,1,0]
df4 = pd.DataFrame(data_d, index=num_l)
df4
df4.loc[2] # custom index 2
df4.iloc[2] # actual index 2 (0, 1, 2, ..)

Towns    Galway
Years      2019
Pop         3.6
Name: 6, dtype: object

# Access and Mutate Members of DataFrame

In [89]:
df2['Tour'] = np.arange(7)
df2
df2.loc['Galway']['Tour']+9 # we may access individual members of the DataFrame
df2
new_values = [3.2, 5.3, 2.9]
df2['Tours'] = pd.Series(new_values, index = ['Galway', 'Shannon', 'Dublin'])
df2

             Pop  Years  Tour  Tours
Cork         1.5   2017     0    NaN
Dublin       1.7   2018     1    2.9
Galway       3.6   2019     2    3.2
Athlone      2.4   2020     3    NaN
Shannon      2.9   2021     4    5.3
Rosscarbery  3.2   2022     5    NaN
Athenry      1.7   2023     6    NaN

# Indexing and Filtering DataFrame

In [92]:
i = ['Waterford', 'Clonakilty', 'Athenry', 'Meath']
c = ['red', 'green', 'gold', 'white']

df5 = pd.DataFrame(np.arange(16).reshape(4,4), index = i, columns=c)
df5

            red  green  gold  white
Waterford     0      1     2      3
Clonakilty    4      5     6      7
Athenry       8      9    10     11
Meath        12     13    14     15

In [108]:
whichRow = df5['gold'] == 14    # here the filter returns the rows along with the matching boolean
whichRow
whichRow = df5[df5['gold'] == 14]   # we may filter and return an entire row
whichRow

        red  green  gold  white
Meath  12.0   13.0  14.0   15.0